imu_filter_madgwick_node:
  ros__parameters:
    use_mag: false
    publish_tf: false
    world_frame: "enu"
    remove_gravity_vector: false
    gain: 0.0005 # reduce gain hopefully reduce noise?
    fixed_frame: "rover_base"
