controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_controller:
      type: joint_state_controller/JointStateBroadcaster
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
joint_state_controller:
  ros__parameters:

ackermann_steering_controller:
  ros__parameters: 
      publish_rate: 50
      velocity_rolling_window_size: 10
      front_wheel_radius: 0.05
      rear_wheel_radius: 0.05
      wheel_base: 0.4
      front_track: 0.3
      rear_track: 0.3
      cmd_vel_timeout: 0.5
      linear.x.has_velocity_limits: true
      linear.x.max_velocity: 2.0
      angular.z.has_velocity_limits: true
      angular.z.max_velocity: 1.0