amcl:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    yaml_filename: "/abs_path_to_map.yaml"
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

local_costmap:
  ros__parameters:
    use_sim_time: false

global_costmap:
  ros__parameters:
    use_sim_time: false
