ekf_filter_node:
  ros__parameters:
    frequency: 100.0
    sensor_timeout: 0.1
    two_d_mode: false # we need 3d elevation data

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: true
    use_control: false

    imu0: /imu_raw
    imu0_config: [false, false, false,   # x, y, z position
                  true,  true,  true,    # roll, pitch, yaw orientation
                  false, false, false,   # x, y, z linear velocity
                  true,  true,  true,    # roll, pitch, yaw angular velocity
                  true,  true,  false]    # x, y, z linear acceleration

    imu0_differential: false # false fuses the pose directly
    imu0_relative: true # treat imu as relative change from initial pose v.s. absolute orientation change from world frame
    imu0_remove_gravitational_acceleration: true # This would offset the imu readings by gravity
    imu0_orientation_covariance: 0.05
    imu0_angular_velocity_covariance: 0.02
    imu0_linear_acceleration_covariance: 999.0  # increasing b/c drift :(

    odom0: /odom
    odom0_config: [true, true, false,     # Position (x, y, z)
                  false, false, false,   # Orientation (use IMU instead)
                  true, true, false,     # Linear velocity (x, y)
                  false, false, false,   # Angular velocity
                  true, true, true]   # Acceleration
    odom0_differential: false
    odom0_relative: true