ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: true
    use_control: false

    imu0: /imu_data
    imu0_config: [false, false, false,   # x, y, z position
                  true,  true,  true,    # roll, pitch, yaw orientation
                  false, false, false,   # x, y, z linear velocity
                  true,  true,  true,    # roll, pitch, yaw angular velocity
                  true,  true,  true]    # x, y, z linear acceleration

    imu0_differential: false # false fuses the pose directly
    imu0_relative: true # treat imu as relative change from initial pose v.s. absolute orientation change from world frame
    imu0_remove_gravitational_acceleration: false # This would offset the imu readings by gravity
