# This did not work, will need to find out why
teleop_twist_joy_node:  
  ros__parameters:
    enable_button: -1  # Disabled (No button required to enable movement)
    require_enable_button: false  # Direct control, no need to press a button

    axis_linear.x: 3  # Right joystick Up/Down for forward/backward motion

    scale_linear.x: 1.0  # Adjust this value for max speed
    scale_linear.y: 0.0  # Not used
    scale_linear.z: 0.0  # Not used

    scale_linear.x_turbo: 2.0  # Turbo mode speed for linear.x
    scale_linear.y_turbo: 0.0  # Turbo mode speed for linear.x
    scale_linear.z_turbo: 0.0  # Turbo mode speed for linear.x

    axis_angular.yaw: 0  # Left joystick Left/Right for steering (turning)

    scale_angular.yaw: 1.5  # Adjust this for steering sensitivity
    scale_angular.yaw_turbo: 3.0  # Turbo mode for steering
