teleop_node:
  ros__parameters:
    axis_linear:
      x: 5 # Mapped to Right trigger
    scale_linear:
      x: 10.0 
    scale_linear_turbo:
      x: 20.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 0 # A
    enable_turbo_button: 1 # B

    require_enable_button: false

# axes:
# 0 - Left Joy (Left, Right) = (1 to -1) Analog
# 1 - Left Joy (Up, Down) = (1 to -1) Analog
# 2 - Left Trigger, 1(unpressed) to -1(pressed) Analog
# 3 -  Right Joy (Left, Right) = (1 to -1) Analog
# 4 - Right Joy (Up, Down) = (1 to -1) Analog
# 5 - Right Trigger, 1(unpressed) to -1(pressed) Analog
# 6 - Dpad Left, Right = (1:-1) Digital
# 7 - D-Pad Up, Down = (1:-1) Digital
# buttons:
# 0 - A
# 1 - B
# 2 - X
# 3 - Y
# 4 - Left Shoulder
# 5 - Right Shoulder
# 6 - Two Squares Button
# 7 - Three Lines Button
# 8 - Lit up X button
# 9 - Left Joy Button
# 10 - Right Joy Button
# 11 - Upload looking button (An up arrow out of a |_| shape)
# ---